"""
Reporter Agent - Generates professional security reports.
"""

from src.sdk.agent import Agent
from src.sdk.tool import function_tool
import os
from datetime import datetime
from pathlib import Path
from typing import List, Dict
import json

# Lazy import helpers — avoid circular imports at module level
def _get_pm():
    """Lazily import and return the profile manager."""
    try:
        from src.repl.profiles import get_profile_manager
        return get_profile_manager()
    except Exception:
        return None


def _get_current_target() -> str:
    """Lazily fetch the active target from the orchestrator context."""
    try:
        from src.agents.orchestrator_agent import get_current_target
        return get_current_target() or ""
    except Exception:
        return ""


@function_tool()
def generate_markdown_report(
    title: str,
    executive_summary: str,
    findings: list[dict] | str,
    recommendations: list[str] | str,
    target: str = "Unknown"
) -> str:
    """
    Generate a markdown security report.
    
    Args:
        title: Report title
        executive_summary: High-level summary
        findings: List of findings with {title, severity, description, evidence} (or JSON string)
        recommendations: List of recommended actions (or JSON string/multiline string)
        target: Target of the assessment
    
    Returns:
        Markdown formatted report
    """
    # Robust argument parsing
    if isinstance(findings, str):
        try:
            findings = json.loads(findings)
        except Exception:
            findings = []
            
    if isinstance(recommendations, str):
        try:
            # Try JSON first
            recommendations = json.loads(recommendations)
        except Exception:
            # Fallback to splitting lines
            recommendations = [r.strip() for r in recommendations.split('\n') if r.strip()]
    
    if not isinstance(findings, list): findings = []
    if not isinstance(recommendations, list): recommendations = []

    report = f"""# {title}

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**Target:** {target}

---

## Executive Summary

{executive_summary}

---

## Findings

"""
    for i, finding in enumerate(findings, 1):
        if not isinstance(finding, dict):
            continue
            
        severity = finding.get('severity', 'INFO')
        severity_badge = {
            'CRITICAL': '🔴',
            'HIGH': '🟠',
            'MEDIUM': '🟡',
            'LOW': '🟢',
            'INFO': '🔵'
        }.get(severity.upper(), '⚪')
        
        report += f"""### {i}. {finding.get('title', 'Finding')} {severity_badge} {severity}

{finding.get('description', '')}

**Evidence:**
```
{finding.get('evidence', finding.get('poc', 'N/A'))}
```

---

"""

    if recommendations:
        report += "## Recommendations\n\n"
        for i, rec in enumerate(recommendations, 1):
            report += f"{i}. {rec}\n"
    
    report += """
---

## Disclaimer

This report is provided for authorized security testing purposes only. 
The findings should be addressed according to organizational risk tolerance.

---

*Generated by Cyber-CoPilot*
"""
    return report


@function_tool()
def save_report(content: str, filename: str = None, output_dir: str = "./reports") -> str:
    """
    Save report to file.
    
    Args:
        content: Report content
        filename: Output filename (auto-generated if not provided)
        output_dir: Output directory
    
    Returns:
        Path to saved report
    """
    try:
        os.makedirs(output_dir, exist_ok=True)
        
        if not filename:
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            filename = f"report_{timestamp}.md"
        
        if filename.lower().endswith(".pdf"):
            return "❌ Error: Use 'generate_pdf_report' for PDF files. 'save_report' only supports text-based formats (md, html, txt)."

        filepath = os.path.join(output_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        
        return f"Report saved to: {filepath}"
    except Exception as e:
        return f"Error saving report: {str(e)}"


@function_tool()
def generate_pdf_report(
    target: str,
    session_dir: str = None,
    findings: List[Dict] = None,
    title: str = None,
) -> str:
    """
    Generate a beautiful professional PDF security report.
    Uses an HTML+CSS template rendered via WeasyPrint → xhtml2pdf → HTML fallback.
    Falls back gracefully when no PDF renderer is installed — saves styled HTML that
    can be printed to PDF from any browser.
    
    Args:
        target: Target domain/IP being assessed
        session_dir: Optional path to session directory for extra context
        findings: List of finding dicts with keys: title, severity, description,
                  evidence/poc, affected_url, remediation, cwe_id, cve_id, cvss_score
        title: Optional custom report title

    Returns:
        Path to generated PDF (or HTML fallback) plus a brief risk summary
    """
    try:
        from src.sdk.report_generator import ReportGenerator as RG, Finding as RGFinding

        report_type = title or f"Security Assessment Report \u2014 {target}"
        gen = RG(target=target, report_type=report_type)

        # Extra context from session dir (best-effort)
        if session_dir and os.path.exists(session_dir):
            _load_session_data(session_dir)

        # Robust finding parsing
        if isinstance(findings, str):
            try:
                findings = json.loads(findings)
            except Exception:
                findings = []

        # Convert finding dicts → Finding objects (map all extended fields)
        cvss_defaults = {"CRITICAL": 9.5, "HIGH": 7.5, "MEDIUM": 5.5, "LOW": 2.5, "INFO": 0.0}
        for fd in (findings or []):
            if not isinstance(fd, dict):
                continue
            sev = fd.get("severity", "INFO").upper()
            gen.add_finding(RGFinding(
                title=fd.get("title", "Unnamed Finding"),
                severity=sev,
                cvss_score=float(fd.get("cvss_score", cvss_defaults.get(sev, 5.0))),
                description=fd.get("description", "No description provided."),
                affected_url=fd.get("affected_url", fd.get("url", target)),
                poc=fd.get("poc", fd.get("evidence", "N/A")),
                remediation=fd.get("remediation", ""),
                cwe_id=fd.get("cwe_id", ""),
                cve_id=fd.get("cve_id", ""),
                cvss_vector=fd.get("cvss_vector", ""),
                why_chosen=fd.get("why_chosen", ""),
                discovery_method=fd.get("discovery_method", ""),
                recon_evidence=fd.get("recon_evidence", ""),
                environment_setup=fd.get("environment_setup", ""),
                steps=fd.get("steps", []),
                expected_output=fd.get("expected_output", ""),
                actual_output=fd.get("actual_output", fd.get("evidence", "")),
                impact=fd.get("impact", ""),
                references=fd.get("references", []),
            ))

        gen.executive_summary = _generate_executive_summary(target, findings)

        from src.sdk.utils import get_project_root
        out_dir = get_project_root() / "reports"
        out_dir.mkdir(parents=True, exist_ok=True)
        result_path = gen.save_pdf(str(out_dir))

        risk  = gen.calculate_risk_rating()
        total = len(gen.findings)
        return (
            f"\u2705 Report saved: {result_path}\n\n"
            f"Findings: {total} | "
            f"Critical: {risk['CRITICAL']} | High: {risk['HIGH']} | "
            f"Medium: {risk['MEDIUM']} | Low: {risk['LOW']} | Info: {risk['INFO']}"
        )
    except Exception as e:
        import traceback
        return f"\u274c Error generating PDF report: {e}\n{traceback.format_exc()}"



def _generate_executive_summary(target: str, findings: List[Dict] = None) -> str:
    """Generate executive summary text."""
    stats = _analyze_findings(findings or [])
    
    summary = f"""This report presents the findings of an automated security assessment conducted on {target} using the Cyber-CoPilot framework.

The assessment identified {stats['total']} security findings across four phases of testing: Reconnaissance, Discovery, Exploitation, and Post-Exploitation.

Key Findings:
- Critical Issues: {stats.get('critical', 0)}
- High Risk Issues: {stats.get('high', 0)}
- Medium Risk Issues: {stats.get('medium', 0)}

The assessment utilized industry-standard tools and methodologies aligned with OWASP guidelines and the MITRE ATT&CK framework. All testing was conducted within the authorized scope."""
    
    if stats.get('critical', 0) > 0:
        summary += "\n\nImmediate action is recommended to address critical vulnerabilities that could lead to system compromise."
    
    return summary


def _analyze_findings(findings: List[Dict]) -> Dict:
    """Analyze findings and generate statistics."""
    stats = {'total': len(findings), 'critical': 0, 'high': 0, 'medium': 0, 'low': 0, 'info': 0}
    
    for f in findings:
        severity = f.get('severity', 'info').lower()
        if severity in stats:
            stats[severity] += 1
    
    return stats




def _load_session_data(session_dir: str) -> Dict:
    """Load session data from the structured TargetProfileManager, falling back to raw profile.json."""
    data: Dict = {}

    # ── 1. Try the live profile manager (most up-to-date source) ──────────────
    try:
        from src.repl.profiles import get_profile_manager
        # Derive the target name from the session path: .../targets/<target>/session_*/
        session_path = Path(session_dir)
        target_dir = session_path.parent
        # parent folder name is the safe-encoded target; use it as the key
        target_hint = target_dir.name  # e.g. "example.com" or "192.168.1.1"
        pm = get_profile_manager()
        profile = pm.load_profile(target_hint)

        if profile.ports or profile.subdomains or profile.vulnerabilities or profile.credentials:
            data = {
                "target": profile.target,
                "ip_addresses": profile.ip_addresses,
                "ports": profile.ports,
                "subdomains": profile.subdomains,
                "vulnerabilities": profile.vulnerabilities,
                "credentials": profile.credentials,
                "web_technologies": profile.web_technologies,
                "web_directories": profile.web_directories,
                "dns_records": profile.dns_records,
                "notes": [n.get("text", "") for n in profile.notes],
            }
            return data
    except Exception:
        pass

    # ── 2. Fall back to raw profile.json on disk ───────────────────────────────
    try:
        session_path = Path(session_dir)
        target_dir = session_path.parent
        profile_path = target_dir / "profile.json"
        if profile_path.exists():
            with open(profile_path, 'r', encoding='utf-8') as f:
                return json.load(f)
    except Exception:
        pass

    return {}


@function_tool()
def get_target_profile(target: str = "") -> str:
    """
    Retrieve the structured recon profile for the current (or specified) target.
    Returns a compact summary of known IPs, ports, subdomains, vulnerabilities,
    credentials, and technology stack — ready to embed in a security report.

    Args:
        target: Optional target override. Defaults to the active session target.

    Returns:
        Human-readable profile brief, or a message if no profile exists.
    """
    t = target.strip() or _get_current_target()
    if not t:
        return "No target is currently set. Provide a target name."

    pm = _get_pm()
    if pm is None:
        return "Profile manager unavailable."

    brief = pm.get_context_brief(t)
    if not brief:
        return f"No recon data found for target '{t}'. Run reconnaissance first."

    # Also pull extended stats for the report
    profile = pm.load_profile(t)
    lines = [f"Target Profile: {t}", ""]
    if profile.ip_addresses:
        lines.append(f"IP Addresses : {', '.join(profile.ip_addresses)}")
    lines.append(f"Open Ports   : {len(profile.ports)}")
    lines.append(f"Subdomains   : {len(profile.subdomains)}")
    lines.append(f"Vulnerabilities: {len(profile.vulnerabilities)}")
    lines.append(f"Credentials  : {len(profile.credentials)}")
    lines.append("")
    lines.append(brief)
    if profile.vulnerabilities:
        lines.append("\nVulnerability Details:")
        for v in profile.vulnerabilities:
            cve = f" ({v.get('cve')})" if v.get('cve') else ""
            lines.append(f"  [{v.get('severity','?').upper()}] {v['name']}{cve}")
            if v.get('description'):
                lines.append(f"      {v['description'][:120]}")
    return "\n".join(lines)


@function_tool()
def create_finding(
    title: str,
    severity: str,
    description: str,
    affected_url: str = "",
    poc: str = "",
    remediation: str = "",
    why_chosen: str = "",
    discovery_method: str = "",
    recon_evidence: str = "",
    environment_setup: str = "",
    steps: list = None,
    expected_output: str = "",
    actual_output: str = "",
    impact: str = "",
    cvss_score: float = 0.0,
    cvss_vector: str = "",
    cwe_id: str = "",
    cve_id: str = "",
    references: list = None,
) -> dict:
    """
    Create a fully-detailed, structured finding entry for a comprehensive security report.

    Args:
        title: Short, specific title — include the vulnerability class and location
               e.g. "SQL Injection in POST /api/v1/login — username parameter"
        severity: CRITICAL, HIGH, MEDIUM, LOW, or INFO
        description: Full technical explanation of the vulnerability class, its root cause
                     in this application, and why this specific implementation is vulnerable.
                     Include the parameter name, data flow, and lack of sanitisation.
        affected_url: Exact URL/endpoint/parameter, e.g. "POST https://target.com/api/login?debug=1"
        poc: Complete, copy-paste-ready exploit command with all flags, payloads, and headers.
             Include sqlmap/dalfox/curl commands with full syntax.
        remediation: Detailed fix with code-level examples where possible.
                     e.g. "Use PDO prepared statements: $stmt = $pdo->prepare('SELECT ... WHERE id=?')"
        why_chosen: Why this endpoint was specifically targeted. Reference the recon data
                    that made it interesting — unusual parameters, error messages, response size
                    anomalies, technology fingerprints, directory listing, etc.
        discovery_method: Which tool and technique found this — e.g.
                         "arjun discovered hidden 'debug' parameter; manual SQLi testing confirmed".
        recon_evidence: Raw tool output that led to this finding, e.g. nmap output,
                        subfinder results, or the ffuf response showing the interesting endpoint.
        environment_setup: Exact commands to install and configure every tool needed to
                           reproduce this PoC from scratch on a fresh Kali Linux machine.
        steps: Numbered list of step-by-step instructions to reproduce — from
               "1. Set up Burp Suite proxy" to "N. Observe database dump in output".
        expected_output: What the attacker sees when exploitation succeeds —
                         database name, table dump, RCE output, session cookie, etc.
        actual_output: Captured tool output confirming exploitability during this test.
        impact: Detailed business and technical impact analysis — what an attacker
                can do with this vulnerability (data theft, RCE, account takeover, etc.)
                and which compliance frameworks are violated (GDPR, PCI-DSS, ISO 27001).
        cvss_score: Numeric CVSS v3.1 base score (0.0–10.0)
        cvss_vector: Full CVSS v3.1 vector string,
                     e.g. "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
        cwe_id: CWE identifier, e.g. "CWE-89" for SQLi, "CWE-79" for XSS
        cve_id: CVE identifier if a known CVE applies, e.g. "CVE-2024-12345"
        references: List of reference URLs — OWASP cheat sheet, CVE, CWE, PortSwigger,
                    HackTricks, exploit-db, MITRE ATT&CK technique

    Returns:
        Fully structured finding dictionary ready for generate_pdf_report()
    """
    cvss_defaults = {"CRITICAL": 9.5, "HIGH": 7.5, "MEDIUM": 5.5, "LOW": 2.5, "INFO": 0.0}
    sev = severity.upper()
    return {
        "title":            title,
        "severity":         sev,
        "cvss_score":       cvss_score or cvss_defaults.get(sev, 5.0),
        "cvss_vector":      cvss_vector,
        "description":      description,
        "affected_url":     affected_url,
        "poc":              poc,
        "remediation":      remediation,
        "why_chosen":       why_chosen,
        "discovery_method": discovery_method,
        "recon_evidence":   recon_evidence[:2000] if recon_evidence else "",
        "environment_setup": environment_setup,
        "steps":            steps or [],
        "expected_output":  expected_output,
        "actual_output":    actual_output[:2000] if actual_output else "",
        "impact":           impact,
        "cwe_id":           cwe_id,
        "cve_id":           cve_id,
        "references":       references or [],
    }


def _build_reporter_instructions() -> str:
    """Build reporter system prompt, injecting a live profile brief when available."""
    target = _get_current_target()
    profile_section = ""
    if target:
        try:
            pm = _get_pm()
            if pm:
                brief = pm.get_context_brief(target)
                if brief:
                    profile_section = f"""

## Current Target Profile

The following recon data has already been collected for **{target}**.
Use this data as the factual basis for your report — do NOT invent findings.

{brief}
"""
        except Exception:
            pass
    return REPORTER_INSTRUCTIONS_TEMPLATE + profile_section


from src.prompts.reporter import REPORTER_INSTRUCTIONS_TEMPLATE
from src.tools.interactive_shell import terminal_screenshot


def create_reporter_agent(model: str = None) -> Agent:
    """
    Create Reporter agent for generating security reports.
    
    Args:
        model: Optional model override
    
    Returns:
        Configured Agent instance
    """
    if model is None:
        from src.sdk.key_manager import get_key_manager
        model = get_key_manager().get_model()

    # 4.8 — Per-finding deliverable bundle generator (curl repro + screenshot
    # + OOB log + CVSS + CWE + markdown REPORT.md). Lives under sdk/, surfaced
    # here because Reporter is the natural place to assemble bug-bounty-ready bundles.
    from src.sdk.report_bundle import generate_finding_bundle

    from src.tools.proxy_manager import proxy_start_anonsurf, proxy_check_ip, proxy_setup_proxychains, proxy_rotate_ip, proxy_status, proxy_stop, proxy_start_tornet
    return Agent(
        name="Reporter",
        instructions=_build_reporter_instructions(),
        model=model,
        tools=[proxy_start_anonsurf, proxy_check_ip, proxy_setup_proxychains, proxy_rotate_ip, proxy_status, proxy_stop, proxy_start_tornet, 
            get_target_profile,
            generate_markdown_report,
            generate_pdf_report,
            save_report,
            create_finding,
            # 4.8 — Per-finding bundle
            generate_finding_bundle,
            # Terminal session screenshots for report evidence
            terminal_screenshot,
        ],
        description="📝 Generate professional security reports"
    )
